#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carparking
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UserData")]
	public partial class qlyreceiptDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReceiptDb(ReceiptDb instance);
    partial void UpdateReceiptDb(ReceiptDb instance);
    partial void DeleteReceiptDb(ReceiptDb instance);
    #endregion
		
		public qlyreceiptDataContext() : 
				base(global::Carparking.Properties.Settings.Default.UserDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public qlyreceiptDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlyreceiptDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlyreceiptDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlyreceiptDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ReceiptDb> ReceiptDbs
		{
			get
			{
				return this.GetTable<ReceiptDb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReceiptDb")]
	public partial class ReceiptDb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDReceipt;
		
		private string _Status;
		
		private int _IDUser;
		
		private string _NameUser;
		
		private int _IDPark;
		
		private string _AreaPark;
		
		private string _IDCar;
		
		private string _Brand;
		
		private string _Color;
		
		private System.DateTime _DateIn;
		
		private System.DateTime _DateOut;
		
		private string _PaymentMethod;
		
		private double _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDReceiptChanging(int value);
    partial void OnIDReceiptChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnIDUserChanging(int value);
    partial void OnIDUserChanged();
    partial void OnNameUserChanging(string value);
    partial void OnNameUserChanged();
    partial void OnIDParkChanging(int value);
    partial void OnIDParkChanged();
    partial void OnAreaParkChanging(string value);
    partial void OnAreaParkChanged();
    partial void OnIDCarChanging(string value);
    partial void OnIDCarChanged();
    partial void OnBrandChanging(string value);
    partial void OnBrandChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnDateInChanging(System.DateTime value);
    partial void OnDateInChanged();
    partial void OnDateOutChanging(System.DateTime value);
    partial void OnDateOutChanged();
    partial void OnPaymentMethodChanging(string value);
    partial void OnPaymentMethodChanged();
    partial void OnPriceChanging(double value);
    partial void OnPriceChanged();
    #endregion
		
		public ReceiptDb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDReceipt", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDReceipt
		{
			get
			{
				return this._IDReceipt;
			}
			set
			{
				if ((this._IDReceipt != value))
				{
					this.OnIDReceiptChanging(value);
					this.SendPropertyChanging();
					this._IDReceipt = value;
					this.SendPropertyChanged("IDReceipt");
					this.OnIDReceiptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUser", DbType="Int NOT NULL")]
		public int IDUser
		{
			get
			{
				return this._IDUser;
			}
			set
			{
				if ((this._IDUser != value))
				{
					this.OnIDUserChanging(value);
					this.SendPropertyChanging();
					this._IDUser = value;
					this.SendPropertyChanged("IDUser");
					this.OnIDUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameUser", DbType="NVarChar(50)")]
		public string NameUser
		{
			get
			{
				return this._NameUser;
			}
			set
			{
				if ((this._NameUser != value))
				{
					this.OnNameUserChanging(value);
					this.SendPropertyChanging();
					this._NameUser = value;
					this.SendPropertyChanged("NameUser");
					this.OnNameUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPark", DbType="Int NOT NULL")]
		public int IDPark
		{
			get
			{
				return this._IDPark;
			}
			set
			{
				if ((this._IDPark != value))
				{
					this.OnIDParkChanging(value);
					this.SendPropertyChanging();
					this._IDPark = value;
					this.SendPropertyChanged("IDPark");
					this.OnIDParkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AreaPark", DbType="NVarChar(50)")]
		public string AreaPark
		{
			get
			{
				return this._AreaPark;
			}
			set
			{
				if ((this._AreaPark != value))
				{
					this.OnAreaParkChanging(value);
					this.SendPropertyChanging();
					this._AreaPark = value;
					this.SendPropertyChanged("AreaPark");
					this.OnAreaParkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCar", DbType="NVarChar(50)")]
		public string IDCar
		{
			get
			{
				return this._IDCar;
			}
			set
			{
				if ((this._IDCar != value))
				{
					this.OnIDCarChanging(value);
					this.SendPropertyChanging();
					this._IDCar = value;
					this.SendPropertyChanged("IDCar");
					this.OnIDCarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand", DbType="NVarChar(50)")]
		public string Brand
		{
			get
			{
				return this._Brand;
			}
			set
			{
				if ((this._Brand != value))
				{
					this.OnBrandChanging(value);
					this.SendPropertyChanging();
					this._Brand = value;
					this.SendPropertyChanged("Brand");
					this.OnBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateIn", DbType="DateTime NOT NULL")]
		public System.DateTime DateIn
		{
			get
			{
				return this._DateIn;
			}
			set
			{
				if ((this._DateIn != value))
				{
					this.OnDateInChanging(value);
					this.SendPropertyChanging();
					this._DateIn = value;
					this.SendPropertyChanged("DateIn");
					this.OnDateInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOut", DbType="DateTime NOT NULL")]
		public System.DateTime DateOut
		{
			get
			{
				return this._DateOut;
			}
			set
			{
				if ((this._DateOut != value))
				{
					this.OnDateOutChanging(value);
					this.SendPropertyChanging();
					this._DateOut = value;
					this.SendPropertyChanged("DateOut");
					this.OnDateOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMethod", DbType="NVarChar(50)")]
		public string PaymentMethod
		{
			get
			{
				return this._PaymentMethod;
			}
			set
			{
				if ((this._PaymentMethod != value))
				{
					this.OnPaymentMethodChanging(value);
					this.SendPropertyChanging();
					this._PaymentMethod = value;
					this.SendPropertyChanged("PaymentMethod");
					this.OnPaymentMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float NOT NULL")]
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
