<?xml version="1.0" encoding="utf-8"?><Database Name="UserData" Class="qlyreceiptDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DANHUYNH\SQLEXPRESS;Initial Catalog=UserData;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="Carparking.Properties.Settings" SettingsPropertyName="UserDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ReceiptDb" Member="ReceiptDbs">
    <Type Name="ReceiptDb">
      <Column Name="IDReceipt" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NameUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDPark" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AreaPark" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDCar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateOut" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PaymentMethod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>